config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  resources :categories do
    resources :payments, only: [:index, :new, :create, :edit, :update]
  end
  resources :payments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index"
end

app/views/shared/_navbar.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link_to @back_link, class: "flex items-center justify-center p-2" do %>
      <i class="fa-solid fa-chevron-left fa-2x"></i>
    <% end %>
    <% if @title %>
      <div class="justify-self-center uppercase text-xl"><%= @title %></div>
    <% end %>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm rounded-lg md:hidden hover:bg-white hover:text-electric focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <i class="fa-solid fa-bars fa-2x"></i>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:items-center md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% if user_signed_in? %>
          <li class="text-lead font-semibold">
            Logged as <%= current_user.email %>
          </li>
          <li>
            <%= link_to 'Categories', categories_path, class: "menu-link" %>
          </li>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "menu-link" %>
          </li>
          <li>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          </li>
        <% else %>
          <li>
            <%= button_to 'Sign in', new_user_session_path, class: "btn btn-confirm" %>
          </li>
          <li>
            <%= link_to 'Sign up', new_user_registration_path, class: "menu-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>