config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  resources :categories do
    resources :payments, only: [:index, :new, :create, :edit, :update]
  end
  resources :payments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  validates_associated :categories
  validates_presence_of :categories
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_user
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :set_category, only: %i[index new]
  # GET /payments or /payments.json
  def index
    @payments = @category.payments
    @categories = Category.where(user: @user)
    @title = 'Payments'
    @back_link = category_path(@category)
  end

  # GET /payments/1 or /payments/1.json
  def show
    @title = @payment.name
    @back_link = @category.nil? ? category_path(@payment.categories.last) : category_path(@category)
  end

  # GET /payments/new
  def new
    @title = 'New Payment'
    @payment = Payment.new
    @payment.categories << @category
    @back_link = category_path(@category)
    @categories = Category.where(user: @user)
  end

  # GET /payments/1/edit
  def edit
    @title = 'Edit payment'
    @categories = Category.where(user: @user)
    @back_link = category_path(@payment.categories.last)
  end

  # POST /payments or /payments.json
  def create
    @categories = Category.where(user: @user)
    @payment = Payment.new(payment_params)
    @payment.user = @user
    back_category = @payment.categories.last
    @back_link = back_category.nil? ? categories_path : category_path(back_category)
    respond_to do |format|
      if @payment.save
        format.html { redirect_to category_url(back_category), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    @categories = Category.where(user: @user)
    respond_to do |format|
      if @payment.update(payment_params)
        format.html do
          redirect_back_or_to category_url(@payment.categories.last), notice: 'Payment was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_back_or_to categories_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, class: "contents") do |form| %>

  <% if payment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field group">
    <%= form.text_field :name, class: text_input_class, placeholder: ' ' %>
    <%= form.label :name, class: label_class %>
  </div>

  <div class="field group">
    <%= form.text_field :amount, class: text_input_class, placeholder: ' ' %>
    <%= form.label :amount, class: label_class %>
  </div>

  <div class="field group">
    <%= form.label :category_ids, 'Categories' %>
    <%= form.collection_check_boxes :category_ids, @categories, :id, :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="actions">
    <%= form.submit class: "cursor-pointer" %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>" class="bg-white flex items-center shadow gap-4 m-4 p-4">
  <div class="flex-grow">
    <div class="my-2 flex justify-between items-end">
      <span class="text-2xl">
        <%= payment.name %>
      </span>
      <span>
        <%= number_to_currency(payment.amount) %>
      </span>
    </div>
    <div class="flex justify-end items-center w-full">
      <span><%= payment.created_at.strftime('%Y-%m-%d') %></span>
      <%= link_to 'Edit', edit_payment_path(payment), class: "rounded-lg p-3 ml-2 bg-gray-100 inline-block font-medium" %>
      <% if action_name != "show" %>
        <%= link_to "Show", payment, class: "rounded-lg p-5 bg-gray-100 inline-block font-medium" %>
      <% else %>
        <%= button_to 'Delete', payment_path(payment), method: :delete, class: "rounded-lg p-3 ml-2 btn-danger inline-block font-medium" %>
      <% end %>
    </div>
    <div class="flex justify-center items-center w-full text-electric-darker">
      <% payment.categories.each do |category| %>
        <%= link_to category do %>
          <i class="<%= icon_class_small(category.icon) %>"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", payment: @payment %>

  <%= link_to "Show this payment", @payment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/payments/index.html.erb
<div class="w-full">

  <div id="payments" class="min-w-full">
    <%= render @payments %>
  </div>
</div>

app/views/payments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", payment: @payment %>

</div>

app/views/payments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto min-w-full">
    <%= render @payment %>
  </div>
</div>