config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  resources :categories do
    resources :payments, only: [:index, :new, :create, :edit, :update]
  end
  resources :payments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :payments

  validates :name, :icon, presence: true

  def total_amount_of_payments
    total = 0
    payments.each { |p| total += p.amount }
    total
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show edit update destroy]
  before_action :set_user
  before_action :set_back_link
  # GET /categories or /categories.json
  def index
    @categories = Category.where(user: @user).order(created_at: :desc)
    @title = 'Categories'
  end

  # GET /categories/1 or /categories/1.json
  def show
    @title = @category.name
    @payments = @category.payments
    @categories = Category.where(user: @user)
  end

  # GET /categories/new
  def new
    @category = Category.new
    @title = 'New Category'
  end

  # GET /categories/1/edit
  def edit
    @title = 'Edit Category'
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = @user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def set_back_link
    @back_link = categories_path
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def icon_class(icon)
    "fa-solid fa-#{icon} fa-3x"
  end

  def icon_class_small(icon)
    "fa-solid fa-#{icon} fa-2x"
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="bg-white flex items-center shadow gap-4 m-4 p-4 last:mb-32">
  <div class="bg-lead text-white rounded-full w-20 h-20 grid place-items-center">
    <%= link_to category do %>
      <i class="<%= icon_class(category.icon) %>" ></i>
    <% end %>
  </div>

  <div class="flex-grow">
    <div class="my-2 flex justify-between items-end">
      <span class="text-2xl">
        <%= link_to category do %>
          <%= category.name %>
        <% end %>
      </span>
      <span>
        <%= number_to_currency(category.total_amount_of_payments) %>
      </span>
    </div>
    <div class="flex justify-end items-center w-full">
      <span><%= category.created_at.strftime('%Y-%m-%d') %></span>
      <%= link_to 'Edit', edit_category_path(category), class: "rounded-lg p-3 ml-2 bg-gray-100 inline-block font-medium" %>
      <% if action_name != "show" %>
        <%= link_to "Show", category, class: "rounded-lg p-5 bg-gray-100 inline-block font-medium" %>
      <% else %>
        <%= button_to 'Delete', category_path(category), method: :delete, class: "rounded-lg p-3 ml-2 btn-danger inline-block font-medium" %>
      <% end %>
    </div>
  </div>
  
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field group">
    <%= form.text_field :name, class: text_input_class, placeholder: ' ' %>
    <%= form.label :name, class: label_class %>
  </div>

  <div class="field group">
    <%= form.text_field :icon, class: text_input_class, placeholder: ' ' %>
    <%= form.label :icon, class: label_class %>
  </div>

  <div class="actions">
    <%= form.submit class: "cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  
  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <div id="categories" class="min-w-full">
    <% if @categories.count > 0 %>
      <%= render @categories %>
    <% else %>
      <h2>There are no categories registered.</h2>
    <% end %>
  </div>

  <div class="actions" data-turbo="true">
    <%= button_to 'New category', new_category_path, method: :get  %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto min-w-full">
    
    <%= render @category %>

    <div class="grid w-full place-items-center">
      <%= link_to new_category_payment_path(@category), class: 'p-2 bg-emerald rounded text-center text-white' do %>
        <i class="fa-solid fa-plus"></i><span class="ml-2">Create Payment</span>
      <% end %>
    </div>

    <%= render @payments %>
  </div>
</div>